global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'bio_trace'
  static_configs:
  - targets: [ 'bio_trace:8080' ]

- job_name: 'otel-collector'
  static_configs:
  - targets: [ 'otel-collector:8888' ]

rule_files:
- '/etc/prometheus/alert.rules.yml'
