{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bio-storage.fullname" . }}-secrets
type: Opaque
stringData:
{{- if .Values.secrets.mongodb.uri }}
  mongodb-uri: {{ .Values.secrets.mongodb.uri | quote }}
{{- end }}
{{- if .Values.secrets.s3.accessKey }}
  aws-access-key-id: {{ .Values.secrets.s3.accessKey | quote }}
{{- end }}
{{- if .Values.secrets.s3.secretKey }}
  aws-secret-access-key: {{ .Values.secrets.s3.secretKey | quote }}
{{- end }}
{{- end }}