name: bio_ai
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.10.7

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.20.2
    # Moved from dev_dependencies to here
    google_fonts: ^6.1.0
    cupertino_icons: ^1.0.8

    # State management
    flutter_riverpod: ^2.3.6

    # Networking
    dio: ^5.3.3

    # Sensors & hardware
    sensors_plus: ^3.0.0
    geolocator: ^10.4.3
    flutter_blue_plus: ^2.1.4
    torch_light: ^0.4.4
    camera: ^0.10.2+6
    permission_handler: ^11.5.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    generate: true
